spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: identity-auth-route
              uri: ${IDENTITY_SERVICE_URI:http://localhost:8081}
              predicates:
                - Path=/api/auth/**

            - id: identity-user-route
              uri: ${IDENTITY_SERVICE_URI:http://localhost:8081}
              predicates:
                - Path=/api/users/**

            - id: media-search-route
              uri: ${MEDIA_SEARCH_SERVICE_URI:http://localhost:8080}
              predicates:
                - Path=/api/search/**

            - id: media-image-route
              uri: ${MEDIA_SEARCH_SERVICE_URI:http://localhost:8080}
              predicates:
                - Path=/api/images/**,/images/**

            - id: interaction-route
              uri: ${INTERACTION_SERVICE_URI:http://localhost:8083}
              predicates:
                - Path=/api/interactions/**

everypicfound:
  auth:
    jwt:
      issuer: ${EPF_JWT_ISSUER:everypicfound-identity}
      audience: ${EPF_JWT_AUDIENCE:everypicfound-api}
      clock-skew: ${EPF_JWT_CLOCK_SKEW:30s}
      public-key-location: ${EPF_JWT_PUBLIC_KEY_LOCATION:file:./config/keys/identity-public.pem}



server:
  port: ${SERVER_PORT:8082}

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

  endpoint:
    health:
      show-details: always
