# 集群名称
brokerClusterName=DefaultCluster
brokerName=broker-a

# 主节点
brokerId=0

#RocketMQ连接Broker的端口
listenPort=10911

# 每天凌晨4点执行过期消息清理检查
deleteWhen=04
#消息文件保留时长(h)
fileReservedTime=72

# Broker 异步复制模式
brokerRole=ASYNC_MASTER
# 同步刷盘
flushDiskType=SYNC_FLUSH

#禁止自动创建topic
autoCreateTopicEnable=false