spring:
  application:
    name: everypicfound-backend
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB

server:
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

everypicfound:
  storage:
    base-path: ./data/images
    access-url-prefix: /images
    max-file-size: 10485760 # 10MB
    allowed-extensions:
      - jpg
      - jpeg
      - png
      - webp

  vector-index:
    active-collection-name: CLIP_v1
    collections:
      CLIP_v1:
        collection-name: CLIP_v1
        model-name: clip-ViT-32B
        vector-dim: 512
        vector-version: v1
        distance-metric: COSINE
    qdrant:
      host: 127.0.0.1
      port: 6334
      use-tls: false
      timeout-ms: 10000