spring:
  application:
    name: everypicfound-backend
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB

server:
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

everypicfound:
  storage:
    base-path: ./data/images
    access-url-prefix: /images
    max-file-size: 10485760 # 10MB
    allowed-extensions:
      - jpg
      - jpeg
      - png
      - webp